package reach.project.push;// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/pushcontainer.proto
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class PushContainer extends Message {
  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_RECEIVERID = 0L;
  public static final Long DEFAULT_SENDERID = 0L;
  public static final Integer DEFAULT_SONGCOUNT = 0;
  public static final List<TransferSong> DEFAULT_TRANSFERSONG = Collections.emptyList();
  public static final String DEFAULT_FIRSTSONGNAME = "hello_world";
  public static final String DEFAULT_USERNAME = "hello_world";
  public static final String DEFAULT_USERIMAGE = "hello_world";

  @ProtoField(tag = 1, type = INT64)
  public final Long receiverId;

  @ProtoField(tag = 2, type = INT64)
  public final Long senderId;

  @ProtoField(tag = 3, type = INT32)
  public final Integer songCount;

  @ProtoField(tag = 4, label = REPEATED, messageType = TransferSong.class)
  public final List<TransferSong> transferSong;

  @ProtoField(tag = 5, type = STRING)
  public final String firstSongName;

  @ProtoField(tag = 6, type = STRING)
  public final String userName;

  @ProtoField(tag = 7, type = STRING)
  public final String userImage;

  public PushContainer(Long receiverId, Long senderId, Integer songCount, List<TransferSong> transferSong, String firstSongName, String userName, String userImage) {
    this.receiverId = receiverId;
    this.senderId = senderId;
    this.songCount = songCount;
    this.transferSong = immutableCopyOf(transferSong);
    this.firstSongName = firstSongName;
    this.userName = userName;
    this.userImage = userImage;
  }

  private PushContainer(Builder builder) {
    this(builder.receiverId, builder.senderId, builder.songCount, builder.transferSong, builder.firstSongName, builder.userName, builder.userImage);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PushContainer)) return false;
    PushContainer o = (PushContainer) other;
    return equals(receiverId, o.receiverId)
        && equals(senderId, o.senderId)
        && equals(songCount, o.songCount)
        && equals(transferSong, o.transferSong)
        && equals(firstSongName, o.firstSongName)
        && equals(userName, o.userName)
        && equals(userImage, o.userImage);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = receiverId != null ? receiverId.hashCode() : 0;
      result = result * 37 + (senderId != null ? senderId.hashCode() : 0);
      result = result * 37 + (songCount != null ? songCount.hashCode() : 0);
      result = result * 37 + (transferSong != null ? transferSong.hashCode() : 1);
      result = result * 37 + (firstSongName != null ? firstSongName.hashCode() : 0);
      result = result * 37 + (userName != null ? userName.hashCode() : 0);
      result = result * 37 + (userImage != null ? userImage.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PushContainer> {

    public Long receiverId;
    public Long senderId;
    public Integer songCount;
    public List<TransferSong> transferSong;
    public String firstSongName;
    public String userName;
    public String userImage;

    public Builder() {
    }

    public Builder(PushContainer message) {
      super(message);
      if (message == null) return;
      this.receiverId = message.receiverId;
      this.senderId = message.senderId;
      this.songCount = message.songCount;
      this.transferSong = copyOf(message.transferSong);
      this.firstSongName = message.firstSongName;
      this.userName = message.userName;
      this.userImage = message.userImage;
    }

    public Builder receiverId(Long receiverId) {
      this.receiverId = receiverId;
      return this;
    }

    public Builder senderId(Long senderId) {
      this.senderId = senderId;
      return this;
    }

    public Builder songCount(Integer songCount) {
      this.songCount = songCount;
      return this;
    }

    public Builder transferSong(List<TransferSong> transferSong) {
      this.transferSong = checkForNulls(transferSong);
      return this;
    }

    public Builder firstSongName(String firstSongName) {
      this.firstSongName = firstSongName;
      return this;
    }

    public Builder userName(String userName) {
      this.userName = userName;
      return this;
    }

    public Builder userImage(String userImage) {
      this.userImage = userImage;
      return this;
    }

    @Override
    public PushContainer build() {
      return new PushContainer(this);
    }
  }
}
