package reach.project.utils;// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/OnboardingData.proto
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class KeyValuePair extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_KEY = "hello_world";
  public static final String DEFAULT_VALUE = "hello_world";

  @ProtoField(tag = 1, type = STRING)
  public final String key;

  @ProtoField(tag = 2, type = STRING)
  public final String value;

  public KeyValuePair(String key, String value) {
    this.key = key;
    this.value = value;
  }

  private KeyValuePair(Builder builder) {
    this(builder.key, builder.value);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof KeyValuePair)) return false;
    KeyValuePair o = (KeyValuePair) other;
    return equals(key, o.key)
        && equals(value, o.value);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = key != null ? key.hashCode() : 0;
      result = result * 37 + (value != null ? value.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<KeyValuePair> {

    public String key;
    public String value;

    public Builder() {
    }

    public Builder(KeyValuePair message) {
      super(message);
      if (message == null) return;
      this.key = message.key;
      this.value = message.value;
    }

    public Builder key(String key) {
      this.key = key;
      return this;
    }

    public Builder value(String value) {
      this.value = value;
      return this;
    }

    @Override
    public KeyValuePair build() {
      return new KeyValuePair(this);
    }
  }
}
